### ISSUE TITLE
[BUG]  Software Update - Compliance by Collection Doesn't load

### ISSUE THREAD

**Issue by Zombierbone** [MEM-Zone/MEM.Zone-Dashboards#36]
**Describe the bug**

**To Reproduce**
1. Go to 'Software Update - Compliance by Collection'
2. Click on 'Collection Name'
3. Scroll down to 'Any Collection'
4. Click on 'View Report'
5. See error An error has occurred during report processing. (rsProcessingAborted)Query execution failed for dataset 'DevicesInfo'. (rsErrorExecutingCommand)
Must declare the scalar variable "@Groups".

**Expected behavior**
The report loads.

**Screenshots**
![Image](https://github.com/user-attachments/assets/d6813383-0b4b-4291-82b9-e7f198501034)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10] Server 2022
 - Browser [e.g. chrome, edge] Edge 
 - Version [e.g. 2.2.0] 137.0.3296.83 (Official build) (64-bit)

**Additional context**

**Comment by Ioan-Popovici** [comment]
Will look into it

**Comment by Zombierbone** [comment]
I have downloaded 6.0.0 and deployed.

I can now see the Update Groups selection

![Image](https://github.com/user-attachments/assets/8f7ed0ec-2d02-40a3-8797-d504c8184f8c)

However after selecting a group and clicking on View Report I get the following error message

An error has occurred during report processing. (rsProcessingAborted)
Query execution failed for dataset 'DevicesInfo'. (rsErrorExecutingCommand)
Must declare the scalar variable "@Locale". Must declare the scalar variable "@LCID". Must declare the scalar variable "@LCID". Incorrect syntax near the keyword 'JOIN'.

![Image](https://github.com/user-attachments/assets/d433247e-9e83-4cd3-a9d1-a28bd40bcdc1)

**Comment by Zombierbone** [comment]
Absolutely, I appreciate the work you do and share, let me know if you need help with debugging / testing.

Thanks

**Comment by Henchman33** [comment]
I am following this as well, Ioan, if you need any help testing I am here for ya.

**Comment by Ioan-Popovici** [comment]
I see that I had a huge change backlog, which I had forgotten about.

I've migrated to some new extensions that were not included in the previous versions.
I was using those privately, and I gave you the new report query instead of the old ones. I could not remember exactly where I left off, so I merged most of the new changes. 

You need to install the new extensions, import the new reports, and then test for bugs.

You can also remove everything and use the installer script to reinstall the dashboards.

@Zombierbone @Henchman33, you can both help here.

**Comment by Zombierbone** [comment]
Thank-you for this, I'll look to do this tomorrow and feedback.

**Comment by Zombierbone** [comment]
Hi,

Managed to install using the installer after clearing out the old dbo.ufn_CM_GetNextMaintenanceWindow (I uncommented the drop function function in the .SQL file).

Still getting the locale issue with the report, however after manually setting the locale using DECLARE @LCID AS INT = 1033; I get a new error.

![Image](https://github.com/user-attachments/assets/65a33c4d-91cd-489c-b1a8-de672d758b19)

Could be due to how I had issues installing maybe.

Thanks again for looking to this and providing the CM community these reports.

**Comment by Ioan-Popovici** [comment]
Great, I'll push the updates, thanks!
